create table public.tickets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  closed_at timestamp with time zone null,
  heading text not null,
  content text not null,
  email text not null,
  is_closed boolean not null,
  closed_by text null,
  last_edited_at timestamp with time zone null,
  created_by uuid not null,
  constraint tickets_pkey primary key (id)
) TABLESPACE pg_default;